### ISSUE TITLE
是否存在数据量限制

### ISSUE THREAD

**Issue by joy-yi0905** [koalaylj/xlsx2json#11]
excel表格如果行数太多，比如几万行，是不是就会导致解析报错啊？我这边好像遇到这个问题了，有办法解决吗？

**Comment by koalaylj** [comment]
大数据还真是没有测过，我是把单个xlsx解析的所有行都放在内存里面拼凑出完整的json再保存的，有可能字符串太大栈溢出了，大约多少行？方便把xlsx共享下么？

**Comment by koalaylj** [comment]
nodejs本身对内存有限制，得需要接触nodejs的内存限制。
