### ISSUE TITLE
导出来的id#id，不是number类型？

### ISSUE THREAD

**Issue by xuzhiping7** [koalaylj/xlsx2json#40]
你好，工具很好用，有个问题问下，这个类型是正确的么？

表格如下：

![1ae54e63-3620-4287-96c9-1ab718d53a57](https://user-images.githubusercontent.com/966372/50263813-ac890100-0452-11e9-9947-367432514f22.png)

导出数据如下，id是string类型。

{
  "1": {
    "id": "1",
    "name": "怪物1",
    "lv": 1,
    "str": 0,
    "agi": 0,
    "pow": 0,
    "ene": 0,
    "hp": 100,
    "mp": 0,
    "minDam": 10,
    "maxDam": 31,
    "defence": 11,
    "doubleAtt": 0,
    "realDam": 1,
    "att_interval": 0.2,
    "icon_path": "monster/0"
  },
  "2": {
    "id": "2",
    "name": "怪物2",
    "lv": 2,
    "str": 0,
    "agi": 0,
    "pow": 0,

**Comment by xuzhiping7** [comment]
文档标注错了，都是id目前都是string，已和大佬确认~

**Comment by zk-luke** [comment]
@xuzhiping7  id都是string类型的。文档示例的json有点问题 稍后我修复下。

**Comment by zk-luke** [comment]
@xuzhiping7  文档修复 下个版本会merge到主干。

**Comment by xuzhiping7** [comment]
@koalaylj  好的，了解了~
