### ISSUE TITLE
【warning】使用时产生警告

### ISSUE THREAD

**Issue by ghost** [koalaylj/xlsx2json#9]
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

**Comment by kevinsong1990** [comment]
I found this issue's reason is we pass wrong/invaild date string to moment construction.  Is that true?

**Comment by koalaylj** [comment]
fixed.
